using System;
using System.Collections.Generic;

/// <summary>
/// Centralized localization manager.
/// Call SetLanguage("FR") or SetLanguage("EN") before building any UI.
/// Use Get(key) to retrieve the localized string.
/// Subscribe to OnLanguageChanged to refresh UI built before the selection.
/// </summary>
public static class LocalizationManager
{
    // ── State ─────────────────────────────────────────────────────────────────
    public static string CurrentLanguage { get; private set; } = "FR";

    /// <summary>Fired when the language is changed. Listeners should rebuild/refresh their text.</summary>
    public static event Action OnLanguageChanged;

    // ── Public API ────────────────────────────────────────────────────────────
    public static void SetLanguage(string lang)
    {
        if (lang != "FR" && lang != "EN") return;
        if (lang == CurrentLanguage) return;
        CurrentLanguage = lang;
        OnLanguageChanged?.Invoke();
    }

    /// <summary>Returns the localized string for <paramref name="key"/>.
    /// Falls back to the key itself if not found.</summary>
    public static string Get(string key)
    {
        var dict = CurrentLanguage == "EN" ? EN : FR;
        return dict.TryGetValue(key, out var value) ? value : key;
    }

    /// <summary>Returns the localized skill name, falling back to <paramref name="fallback"/>.</summary>
    public static string GetSkillName(string skillId, string fallback)
    {
        string key = "skill_name_" + skillId;
        var dict = CurrentLanguage == "EN" ? EN : FR;
        return dict.TryGetValue(key, out var v) ? v : fallback;
    }

    /// <summary>Returns the localized skill description, falling back to <paramref name="fallback"/>.</summary>
    public static string GetSkillDesc(string skillId, string fallback)
    {
        string key = "skill_desc_" + skillId;
        var dict = CurrentLanguage == "EN" ? EN : FR;
        return dict.TryGetValue(key, out var v) ? v : fallback;
    }

    /// <summary>Returns the localized skill variableModified text, falling back to <paramref name="fallback"/>.</summary>
    public static string GetSkillVar(string skillId, string fallback)
    {
        string key = "skill_var_" + skillId;
        var dict = CurrentLanguage == "EN" ? EN : FR;
        return dict.TryGetValue(key, out var v) ? v : fallback;
    }

    // ── French strings ────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> FR = new Dictionary<string, string>
    {
        // ── Main Menu ─────────────────────────────────────────────────────────
        { "menu_tagline",        "Dominez le monde. Un caca à la fois." },
        { "menu_play_btn",       "JOUER" },

        // ── Virus Selection Panel ─────────────────────────────────────────────
        { "vsp_title",           "CHOISISSEZ VOTRE VIRUS" },
        { "vsp_patient0_title",  "PAYS DU PATIENT 0" },
        { "vsp_btn_start_ready", "DÉMARRER L'INFECTION" },
        { "vsp_btn_start_hint",  "Sélectionnez un virus et un pays" },
        { "vsp_loading_title",   "GÉNÉRATION DU CROTTE VIRUS" },
        { "vsp_loading_sub",     "Caca is loading..." },

        // Continent filter buttons
        { "continent_all",       "TOUS" },
        { "continent_europe",    "EUROPE" },
        { "continent_asia",      "ASIE" },
        { "continent_africa",    "AFRIQUE" },
        { "continent_northam",   "AMER. NORD" },
        { "continent_southam",   "AMER. SUD" },
        { "continent_oceania",   "OCEANIE" },
        { "continent_other",     "AUTRES" },

        // Virus data
        { "virus_name_classique",            "La Crottance" },
        { "virus_tagline_classique",         "Virus classique équilibré" },
        { "virus_desc_classique",            "Né dans les élevages industriels de la plaine beauce, La Crottance est un pathogène polyvalent qui s'adapte à tous les environnements. Il prospère aussi bien dans les grandes villes que dans les campagnes reculées." },
        { "virus_caps_classique",            "Transmission équilibrée · Bonne résistance au froid · Exploite les inégalités sociales" },

        { "virus_name_cacastellaire",        "Cacastellaire" },
        { "virus_tagline_cacastellaire",     "Pathogène à dispersion atmosphérique" },
        { "virus_desc_cacastellaire",        "Découvert en orbite basse par un satellite espion défaillant, le Cacastellaire se propage dans les courants d'air à haute altitude. Les aéroports sont ses meilleurs alliés." },
        { "virus_caps_cacastellaire",        "Excellente propagation aérienne · Bonus sur les transports internationaux · Faible résistance à la chaleur" },

        { "virus_name_nanocaca",             "Nano Caca" },
        { "virus_tagline_nanocaca",          "Nano-pathogène furtif et létal" },
        { "virus_desc_nanocaca",             "Résultat d'une expérience de bio-ingénierie militaire mal maîtrisée, le Nano Caca est indétectable par les systèmes de surveillance sanitaire classiques. Sa létalité élevée en fait un adversaire redoutable." },
        { "virus_caps_nanocaca",             "Invisible aux systèmes de détection précoce · Létal dès le départ · Propagation lente" },

        { "virus_name_fungicaca",            "Fongi-Caca" },
        { "virus_tagline_fungicaca",         "Mycose fongique à croissance lente" },
        { "virus_desc_fungicaca",            "Mutant du Candida auris découvert dans les réseaux d'égouts de Mumbai, le Fongi-Caca prospère dans les zones humides et tropicales. Sa résistance totale aux antifongiques le rend quasi intraitable." },
        { "virus_caps_fungicaca",            "Résistance aux médicaments · Prospère dans les zones tropicales · Croissance lente mais inexorable" },

        // ── Patient Zero Selection Panel ──────────────────────────────────────
        { "pz_title",            "CHOISISSEZ LE PAYS CIBLE" },
        { "pz_btn_confirm",      "CONFIRMER" },

        // ── Skill Tree Menu UI ────────────────────────────────────────────────
        { "skill_tab_transmission",          "Transmission" },
        { "skill_tab_mortalite",             "Mortalité" },
        { "skill_tab_special",               "Spécial" },

        { "skill_info_default_title_transmission", "Transmission" },
        { "skill_info_default_desc_transmission",  "Clique sur un skill rouge pour voir ses détails puis achète-le avec tes Crotogènes. Les skills L2 gris se débloquent après achat du L1." },
        { "skill_info_default_desc_special",       "Clique sur un skill pour voir ses détails. Les skills N2 et plus se débloquent après achat des prérequis. Tous les skills Spécial sont gratuits." },
        { "skill_coming_soon_desc",                "Contenu bientôt disponible. Cet onglet sera implémenté dans une prochaine phase." },

        { "skill_btn_buy_default",           "ACHETER" },
        { "skill_btn_buy_label",             "Acheter" },
        { "skill_btn_already_bought",        "Acheté" },
        { "skill_btn_buy_with_cost",         "Acheter ({0})" },
        { "skill_cost_display",              "Coût: {0} | Points: {1}" },
        { "skill_cant_buy_suffix",           "{0} (Achat impossible)" },
        { "skill_prereq_unmet",              "Prérequis non remplis pour ce skill." },
        { "skill_insufficient_points",       "Points insuffisants : coût {0}, tu as {1}." },
        { "skill_buy_fail_unknown",          "Achat impossible pour une raison inconnue." },
        { "skill_buy_success_notif",         "MUTATION VIRALE AUTONOME" },

        // ── Top Bar HUD ───────────────────────────────────────────────────────
        { "hud_btn_hide",        "v Cacher" },
        { "hud_btn_show",        "^ Afficher" },
        { "hud_day_label",       "Jour {0}" },
        { "hud_btn_slow",        "<< Lent" },
        { "hud_btn_normal",      "Normal" },
        { "hud_btn_pause",       "|| Pause" },
        { "hud_btn_resume",      "> Reprendre" },
        { "hud_btn_fast",        ">> Vite" },

        // ── Points Display ────────────────────────────────────────────────────
        { "points_label",        "Crotogènes: {0}" },

        // ── End Screen ────────────────────────────────────────────────────────
        { "end_headline_victory",  "EXTINCTION ACCOMPLIE" },
        { "end_headline_healed",   "LE VACCIN A TRIOMPHÉ" },
        { "end_headline_defeat",   "LE VIRUS EST ÉTEINT" },
        { "end_sub_victory",       "L'humanité a été anéantie. Votre virus a réussi sa mission." },
        { "end_sub_healed",        "La science a vaincu. L'humanité a survécu grâce au vaccin." },
        { "end_sub_defeat",        "Votre infection s'est éteinte avant d'éliminer l'humanité." },
        { "end_stat_virus",        "Virus : {0}" },
        { "end_stat_turns",        "Durée de la partie : <b>{0}</b> tours" },
        { "end_stat_dead",         "Total morts          : <b>{0}</b>" },
        { "end_stat_infected",     "Total infectés       : <b>{0}</b>" },
        { "end_btn_replay",        "REJOUER" },

        // ── Status Bar ──────────────────────────────────────────────────────
        { "statusbar_infected",   "Infectés: {0}" },
        { "statusbar_vaccine",    "Vaccin: {0}%" },

        // ── Transmission Skills ────────────────────────────────────────────
        { "skill_name_airborneL1",   "Diérhée Aéroportée" },
        { "skill_desc_airborneL1",   "Des aérosols fécaux atteignent l'altitude de croisière. Même les passagers en première classe ne sont pas en sécurité." },
        { "skill_var_airborneL1",    "Nouveau modificateur bonus pour la propagation aérienne." },
        { "skill_name_airborneL2",   "Chemtrails de Contamination" },
        { "skill_desc_airborneL2",   "Les chemtrails existent pour de bon... mais relâchent du caca au-dessus des populations." },
        { "skill_var_airborneL2",    "L'impact de la propagation aérienne est encore plus fort." },
        { "skill_name_seaL1",        "Buffets Piège" },
        { "skill_desc_seaL1",        "Les buffets à volonté dans les restaurants des bateaux de croisière deviennent un terrain de contamination." },
        { "skill_var_seaL1",         "Nouveau modificateur bonus pour la propagation maritime." },
        { "skill_name_seaL2",        "Océan de Saleté" },
        { "skill_desc_seaL2",        "Les bateaux de croisière ne sont plus que des toilettes flottantes géantes." },
        { "skill_var_seaL2",         "L'impact de la propagation maritime est encore plus fort." },
        { "skill_name_landL1",       "Pompe dans le Cul" },
        { "skill_desc_landL1",       "Un infecté a mis la pompe à essence dans son cul, créant un réseau géant de propagation via les stations-service." },
        { "skill_var_landL1",        "Nouveau modificateur bonus pour la propagation terrestre." },
        { "skill_name_landL2",       "Mario CaCart" },
        { "skill_desc_landL2",       "La fumée d'échappement transforme les routes en autoroutes de contamination." },
        { "skill_var_landL2",        "L'impact de la propagation terrestre est encore plus fort." },
        { "skill_name_coldL1",       "Survivant de la Crotte Gelée" },
        { "skill_desc_coldL1",       "Votre virus évolue pour prospérer dans les salles de bains russes. La vodka ne le tue pas." },
        { "skill_var_coldL1",        "Nouveau modificateur bonus pour la résistance au froid." },
        { "skill_name_coldL2",       "Maître de la Crotte Arctique" },
        { "skill_desc_coldL2",       "Les souches sibériennes deviennent le climat préféré de votre virus. La crotte de pingouin le propage encore plus loin." },
        { "skill_var_coldL2",        "L'impact de la résistance au froid est encore plus fort." },
        { "skill_name_heatL1",       "Adaptation Diarrhée Désertique" },
        { "skill_desc_heatL1",       "Les salles de bains de Death Valley ne peuvent tuer cette souche. Même la crotte de scorpion transporte votre virus." },
        { "skill_var_heatL1",        "Nouveau modificateur bonus pour la résistance à la chaleur." },
        { "skill_name_heatL2",       "Fournaise de Saloperies" },
        { "skill_desc_heatL2",       "Les infections prospèrent à 50°C. La merde chaude et liquide s'écoule partout et contamine tout ce qui bouge." },
        { "skill_var_heatL2",        "L'impact de la résistance à la chaleur est encore plus fort." },
        { "skill_name_bathroomL1",   "Spray Sans Douche" },
        { "skill_desc_bathroomL1",   "Les pays sans systèmes de lavage propagent votre gloire. Mains sèches = mains contaminées." },
        { "skill_var_bathroomL1",    "Nouveau modificateur bonus pour l'exploitation du manque d'hygiène." },
        { "skill_name_bathroomL2",   "Attaque des Toilettes Japonaises" },
        { "skill_desc_bathroomL2",   "Les dysfonctionnements de bidet high-tech envoient des germes partout. Les riches se font détruire par des toilettes conscientes." },
        { "skill_var_bathroomL2",    "L'impact de l'exploitation des différences de richesse est encore plus fort." },
        { "skill_name_dogL1",        "Pandémie de Caniche" },
        { "skill_desc_dogL1",        "Les chiens développent une diarrhée infectée. Chaque défécation publique propage votre chef-d'œuvre." },
        { "skill_var_dogL1",         "Nouveau modificateur bonus pour la propagation via les chiens." },
        { "skill_name_dogL2",        "Dévastation Great Dane" },
        { "skill_desc_dogL2",        "Les crottes de chiens géants contiennent des charges virales qui font jalouser les laboratoires. Les chiens errants deviennent votre armée involontaire." },
        { "skill_var_dogL2",         "L'impact de la propagation via les chiens est encore plus fort." },
        { "skill_name_petL1",        "Silencieux Mais Mortel" },
        { "skill_desc_petL1",        "Les humains infectés deviennent des distributeurs ambulants de péts. Chaque bureau, ascenseur et trajet en bus devient une attaque d'aérosols viraux." },
        { "skill_var_petL1",         "Nouveau modificateur bonus pour la propagation via les gaz digestifs humains." },
        { "skill_name_petL2",        "Apocalypse Méthane" },
        { "skill_desc_petL2",        "Les systèmes digestifs humains deviennent des armes biologiques. Les foules de concerts, restaurants et transports propagent votre virus sur de l'air chaud." },
        { "skill_var_petL2",         "L'impact de la propagation via les gaz digestifs humains est encore plus fort." },
        { "skill_name_flyL1",        "Service de Messagerie à Mouches" },
        { "skill_desc_flyL1",        "Les mouches se posent sur des fèces, puis sur de la nourriture. Votre virus voyage de repas en repas à travers les villages." },
        { "skill_var_flyL1",         "Nouveau modificateur bonus pour la propagation via les mouches." },
        { "skill_name_flyL2",        "Armée d'Insectes" },
        { "skill_desc_flyL2",        "Des trillions de mouches deviennent votre réseau de livraison. Égouts ouverts = paradis viral." },
        { "skill_var_flyL2",         "L'impact de la propagation via les mouches est encore plus fort." },
        { "skill_name_urineL1",      "Flot Doré" },
        { "skill_desc_urineL1",      "L'urine infectée contamine les réseaux d'eau. Les sols de toilettes deviennent des patinoires de la perdition." },
        { "skill_var_urineL1",       "Nouveau modificateur bonus pour la transmission par l'urine contaminée." },
        { "skill_name_urineL2",      "Blitzkrieg de la Vessie" },
        { "skill_desc_urineL2",      "Les infections urinaires propagent votre virus à chaque chasse d'eau. Les systèmes d'eau dans le monde entier s'inclinent devant votre supermancie." },
        { "skill_var_urineL2",       "L'impact de la transmission par l'urine contaminée est encore plus fort." },
        { "skill_name_drugL1",       "Briseur d'Antibiotiques" },
        { "skill_desc_drugL1",       "La pénicilline ? Mignon. Votre virus se moque des antibiotiques et continue de se propager." },
        { "skill_var_drugL1",        "Nouveau modificateur bonus pour la résistance aux antibiotiques." },
        { "skill_name_drugL2",       "Super Bug Evolution" },
        { "skill_desc_drugL2",       "Chaque antibiotique vous rend plus fort. Les hôpitaux sont votre salle de sport. La science médicale capitule." },
        { "skill_var_drugL2",        "L'impact de la résistance aux antibiotiques est encore plus fort." },
        { "skill_name_vaccineL1",    "ViteMaDose" },
        { "skill_desc_vaccineL1",    "Le virus n'a peur de personne, même ceux naturellement immunités." },
        { "skill_var_vaccineL1",     "Nouveau modificateur bonus pour le contournement de l'immunité vaccinale." },
        { "skill_name_vaccineL2",    "Immunité ? Lol." },
        { "skill_desc_vaccineL2",    "L'immunité collective est un mythe. Votre virus traite les anticorps comme des amuse-gueules." },
        { "skill_var_vaccineL2",     "L'impact du contournement de l'immunité vaccinale est encore plus fort." },
        { "skill_name_vaccineSabotageL1", "Caca dans les Pipettes" },
        { "skill_desc_vaccineSabotageL1", "Un mystérieux parfum fécal envahit le labo. Les chercheurs n'arrêtent pas d'éternuer et font tomber leurs échantillons." },
        { "skill_var_vaccineSabotageL1",  "Nouveau modificateur pour le ralentissement de la recherche vaccinale." },
        { "skill_name_vaccineSabotageL2", "Guerre Bactériologique des WC" },
        { "skill_desc_vaccineSabotageL2", "La machine à café des scientifiques sent maintenant l'apocalypse. Entre urgences toilettes et gants contaminés, l'équipe vaccin avance à vitesse d'escargot." },
        { "skill_var_vaccineSabotageL2",  "L'impact du ralentissement de la recherche vaccinale est encore plus fort." },
        { "skill_name_fusionBioBidetL3",    "Bio-Bidet Catastrophe" },
        { "skill_desc_fusionBioBidetL3",    "Les bidets, traînées d'urine et systèmes de plomberie se synchronisent en un seul moteur de contamination mondial." },
        { "skill_var_fusionBioBidetL3",     "Les impacts de l'exploitation du manque d'hygiène et de la transmission par l'urine sont encore plus forts." },
        { "skill_name_fusionMethaneBurstL3", "Explosion de Vecteur Méthane" },
        { "skill_desc_fusionMethaneBurstL3", "Les péts humains ne se dispersent plus dans l'air, créant des nuages de contamination qui se propagent rapidement." },
        { "skill_var_fusionMethaneBurstL3",  "Les impacts de la propagation via les gaz digestifs et la propagation aérienne sont encore plus forts." },
        { "skill_name_fusionCanineAirliftL3", "Aéroport de Crottes Canines" },
        { "skill_desc_fusionCanineAirliftL3", "Les mouches transportent les excréments infectés des chiens à travers le monde, facilitant la propagation rapide du virus." },
        { "skill_var_fusionCanineAirliftL3",  "Les impacts via les chiens, mouches et l'exploitation du manque d'hygiène sont encore plus forts." },

        // ── Mortalité Skills ─────────────────────────────────────────────
        { "skill_name_anusL1",   "Fissures Anales Spontanées" },
        { "skill_desc_anusL1",   "L'épithélium rectal se déchire spontanément. Chaque passage provoque une hémorragie mineure. Le système immunitaire commence à échouer face à l'inflammation constante." },
        { "skill_var_anusL1",    "Mortalité augmentée, avec bonus renforcé dans les pays froids." },
        { "skill_name_anusL2",   "Prolapsus Muqueux Complet" },
        { "skill_desc_anusL2",   "La muqueuse rectale s'effondre et s'expulse. Les sphincters ne peuvent plus retenir quoi que ce soit. Les médecins ne savent plus quoi faire." },
        { "skill_var_anusL2",    "Mortalité encore plus élevée, surtout dans les pays froids." },
        { "skill_name_anusL3",   "Nécrose du Sphincter" },
        { "skill_desc_anusL3",   "Le tissu rectal meurt. Tout le système gastro-intestinal inférieur se transforme en plaie ouverte. La gangrène s'installe." },
        { "skill_var_anusL3",    "Hémorragie maximale : mortalité très forte en froid, excellente base de létalité partout." },
        { "skill_name_poumonL1", "Reflux Méthanique Chronique" },
        { "skill_desc_poumonL1", "Les gaz intestinaux remontent jusqu'aux poumons. Chaque respiration sent et brûle. La capacité vitale décline de 5 % par jour." },
        { "skill_var_poumonL1",  "Dégâts respiratoires renforcés en pays chauds ou clima arides." },
        { "skill_name_poumonL2", "Solidification Bronchique" },
        { "skill_desc_poumonL2", "La matière fécale se durcit dans les bronches. La toux produit des caillots marron. L'hypoxie commence. Les patients s'étouffent lentement." },
        { "skill_var_poumonL2",  "Asphyxie plus violente, surtout en chaud/aride." },
        { "skill_name_poumonL3", "Inondation Pulmonaire Fécale" },
        { "skill_desc_poumonL3", "Les alvéoles se remplissent de liquide intestinal. Le patient ne peut plus respirer normalement. La noyade interne est inévitable." },
        { "skill_var_poumonL3",  "Asphyxie extrême : pic de mortalité en chaud/aride." },
        { "skill_name_bouffeL1", "Infiltration des Cultures" },
        { "skill_desc_bouffeL1", "Les cultures agricoles sont contaminées par du fumier viral. Les récoltes deviennent des vecteurs passifs." },
        { "skill_var_bouffeL1",  "Contamination alimentaire surtout efficace en faible hygiène." },
        { "skill_name_bouffeL2", "Chaîne de Distribution Corrompue" },
        { "skill_desc_bouffeL2", "Les usines alimentaires sont devenues des incubateurs. Chaque étape de transformation amplifie la charge virale." },
        { "skill_var_bouffeL2",  "Contamination alimentaire amplifiée si hygiène basse, encore plus en pays chauds." },
        { "skill_name_bouffeL3", "Apocalypse du Marché Mondial" },
        { "skill_desc_bouffeL3", "Chaque aliment sur terre est infecté. Du champ à l'assiette, tout est contaminé. La famine tue avant la maladie." },
        { "skill_var_bouffeL3",  "Contamination maximale : très punissant en faible hygiène, avec surbonus en chaud." },
        { "skill_name_cerveauL1", "Encéphalite Fécale" },
        { "skill_desc_cerveauL1", "Les bactéries fécales franchissent la barrière hémato-encéphalique. Le cerveau marine doucement dans la crotte." },
        { "skill_var_cerveauL1",  "Dégâts mentaux actifs surtout dans les pays riches." },
        { "skill_name_cerveauL2", "Pression Crânienne Brun Foncé" },
        { "skill_desc_cerveauL2", "Les cavités cérébrales se remplissent de matière brune. Les yeux commencent à suinter. La couleur est indescriptible." },
        { "skill_var_cerveauL2",  "Colonisation cérébrale renforcée en pays riches." },
        { "skill_name_cerveauL3", "Excrétion Oculaire Terminale" },
        { "skill_desc_cerveauL3", "Le cerveau se vide par les orbites. Les larmes sont maintenant d'une nuance marron inquiétante. Les neurologues ont abandonné." },
        { "skill_var_cerveauL3",  "Dégâts mentaux majeurs : effet maximal dans les pays riches." },
        { "skill_name_folieL1",   "Psychose Digestive" },
        { "skill_desc_folieL1",   "Les neurotransmetteurs intestinaux envahissent le cerveau. La frontière entre envies et instincts s'efface." },
        { "skill_var_folieL1",    "Folie merdique : dégâts mentaux surtout visibles en pays riches." },
        { "skill_name_folieL2",   "Délire Stercoral" },
        { "skill_desc_folieL2",   "Le patient voit des couleurs que les toilettes ne devraient pas avoir. Hallucinations garanties. Le calme ne sert à rien." },
        { "skill_var_folieL2",    "Folie merdique renforcée, surtout en pays riches." },
        { "skill_name_folieL3",   "Démence Terminale des Latrines" },
        { "skill_desc_folieL3",   "Le patient est convaincu d'être une toilette. Phase finale : il essaie de s'utiliser lui-même." },
        { "skill_var_folieL3",    "Démence terminale : pression mentale maximale dans les pays riches." },
        { "skill_name_fusionLiquefactionL4", "Liquéfaction Fécale Totale" },
        { "skill_desc_fusionLiquefactionL4", "Corps qui se désagrège par tous les vecteurs. Fèces hémorragiques, respiration d'excréments, aliments qui saignent. La désintégration est totale." },
        { "skill_var_fusionLiquefactionL4",  "Fusion Anus+Poumon : létalité massive en pays froids et en zones chaudes/arides." },
        { "skill_name_fusionApoéoseL4",       "Apoéose Mentale Excrétoire" },
        { "skill_desc_fusionApoéoseL4",       "Cerveau de caca qui rend fou. Le patient expulse ses pensées par l'anus. La conscience se dissout dans les fèces. Démence absolue." },
        { "skill_var_fusionApoéoseL4",        "Fusion Cerveau+Folie : dégâts mentaux extrêmes, actifs surtout dans les pays riches." },
        { "skill_name_fusionContaminationL4", "Contamination Psycho-Respiratoire" },
        { "skill_desc_fusionContaminationL4", "Noyade interne, empoisonnement alimentaire et démence simultanés. La folie aggrave chaque respiration, chaque bouchée devient délire. Triple asphyxie." },
        { "skill_var_fusionContaminationL4",  "Fusion Poumon+Bouffe : énorme pression en chaud/aride, et en faible hygiène surtout si chaud." },

        // ── Special Skills ──────────────────────────────────────────────────
        { "skill_name_claN1",  "CrotteSpreading Evolution" },
        { "skill_desc_claN1",  "Le virus évolue en continu pour crotter un maximum d'humains. Chaque tour, 2 % de chance d'assimiler automatiquement un talent de transmission." },
        { "skill_var_claN1",   "2 % chance/tour : déblocage auto d'un skill Transmission" },
        { "skill_name_claN2a", "Bave Crottée" },
        { "skill_desc_claN2a", "Le virus a impregné la salive de tous les chiens. Propagation canine et animale améliorée." },
        { "skill_var_claN2a",  "+0.09 modificateur Chien et Animaux" },
        { "skill_name_claN2b", "Flaquacaca" },
        { "skill_desc_claN2b", "Même les simples flaques d'eau innocentes deviennent maintenant un moyen de propagation. Propagation terrestre améliorée." },
        { "skill_var_claN2b",  "+0.07 modificateur Transport terrestre" },
        { "skill_name_claN3",  "Prime Coprogène" },
        { "skill_desc_claN3",  "Chaque infection rapporte désormais un loyer biologique permanent. Bonus de gains de points définitif pour toute la partie." },
        { "skill_var_claN3",   "+22 % gain de points définitif" },
        { "skill_name_claN4a", "Colique Invasive" },
        { "skill_desc_claN4a", "La dernière mutation transforme les coliques en hémorragie systémique. Létalité augmentée." },
        { "skill_var_claN4a",  "+3.5 % létalité" },
        { "skill_name_claN4b", "Croûte Septique" },
        { "skill_desc_claN4b", "Dans les environnements insalubres, le virus développe une couche de crasse biologique qui décuple sa virulence." },
        { "skill_var_claN4b",  "+0.06 exploitation Hygiène" },
        { "skill_name_casN1",  "Dispersion Spatiale" },
        { "skill_desc_casN1",  "Par un phénomène de déjection orbitale, le virus se dissémine instantanément sur 5 pays aléatoires non infectés lors de l'achat." },
        { "skill_var_casN1",   "Infecte immédiatement 5 pays aléatoires (1 personne chacun)" },
        { "skill_name_casN2a", "Poussière de Merde Orbitale" },
        { "skill_desc_casN2a", "Les particules de déjection cosmique infiltrent avions et bateaux sans effort." },
        { "skill_var_casN2a",  "+0.10 transport Aérien | +0.08 transport Maritime" },
        { "skill_name_casN2b", "Plasma Coproïde" },
        { "skill_desc_casN2b", "L'origine extraterrestre confère une résistance aux températures extrêmes." },
        { "skill_var_casN2b",  "+0.05 résistance Chaleur | +0.05 résistance Froid" },
        { "skill_name_casN3",  "Transmission Évolutive Astrale" },
        { "skill_desc_casN3",  "Le signal cosmique s'ancre définitivement dans le virus : 2 % de chance permanente par tour d'assimiler automatiquement un skill de transmission." },
        { "skill_var_casN3",   "+2 % chance/tour permanent : déblocage auto d'un skill Transmission" },
        { "skill_name_casN4a", "Halo Nécrotique" },
        { "skill_desc_casN4a", "L'aura de mort cosmique irradie les tissus, augmentant la létalité du virus." },
        { "skill_var_casN4a",  "+4 % létalité" },
        { "skill_name_casN4b", "Gravité Fécale" },
        { "skill_desc_casN4b", "Un virus spatial n'a aucune limite, les frontières ne peuvent le contenir." },
        { "skill_var_casN4b",  "+0.07 propagation transfrontalière" },
        { "skill_name_nanN1",  "Injection Patient Zéro" },
        { "skill_desc_nanN1",  "Un nano-porteur autonome s'infiltre discrètement dans un pays non infecté et dépose précisément 1 porteur asymptomatique." },
        { "skill_var_nanN1",   "Infecte immédiatement 1 personne dans un pays non infecté aléatoire" },
        { "skill_name_nanN2a", "Blindage Pharmaceutique" },
        { "skill_desc_nanN2a", "Les nano-coques renforcent la membrane virale contre les antiviraux. Les traitements perdent de leur efficacité." },
        { "skill_var_nanN2a",  "+0.10 résistance aux médicaments" },
        { "skill_name_nanN2b", "Auto-Réplication Optimisée" },
        { "skill_desc_nanN2b", "Les nano-capteurs optimisent le taux de réplication en temps réel. La croissance des infections s'accélère." },
        { "skill_var_nanN2b",  "+0.08 multiplicateur de croissance d'infection" },
        { "skill_name_nanN3",  "Mutation CacaTueuse Autonome" },
        { "skill_desc_nanN3",  "Les processeurs nano-viraux s'ancrent définitivement et forgent en permanence de nouveaux symptômes mortels." },
        { "skill_var_nanN3",   "+4 % chance/tour permanent : déblocage auto d'un skill Mortalité" },
        { "skill_name_nanN4a", "Essaim de Colonisation" },
        { "skill_desc_nanN4a", "Les nano-virus ciblent prioritairement les individus aisés, dont les réseaux sociaux assurent une dissémination maximale." },
        { "skill_var_nanN4a",  "+0.06 exploitation Richesse" },
        { "skill_name_nanN4b", "Protocole Sphincter-0" },
        { "skill_desc_nanN4b", "Le protocole final contourne les défenses immunitaires génétiques tout en augmentant la virulence létale." },
        { "skill_var_nanN4b",  "+4 % létalité | +4 % contournement Immunité" },
        { "skill_name_myoN1",  "Mutation Sporulée" },
        { "skill_desc_myoN1",  "Le mycélium viral sporule spontanément. 2 % de chance par tour d'acquérir un symptôme létal." },
        { "skill_var_myoN1",   "2 % chance/tour : déblocage auto d'un skill Mortalité" },
        { "skill_name_myoN2a", "Réseau d'Égouts" },
        { "skill_desc_myoN2a", "Le champignon colonise les réseaux d'égouts. Les environnements à faible hygiène deviennent de parfaits incubateurs." },
        { "skill_var_myoN2a",  "+0.09 exploitation Hygiène" },
        { "skill_name_myoN2b", "Racines Intestinales" },
        { "skill_desc_myoN2b", "Les hyphes virales s'ancrent profondément dans les tissus intestinaux, accélérant la croissance de l'infection." },
        { "skill_var_myoN2b",  "+0.07 croissance d'infection" },
        { "skill_name_myoN3",  "Synthétisation Difficile" },
        { "skill_desc_myoN3",  "Le champignon produit des protéines mimant les anticorps naturels, rendant le développement du vaccin extrêmement complexe. Plafond vaccin à 115 %." },
        { "skill_var_myoN3",   "Plafond vaccin relevé à 115 %" },
        { "skill_name_myoN4a", "Floraison Champigno-Fécale" },
        { "skill_desc_myoN4a", "Dans les environnements humides, les spores virales fleurissent en agents nécrotiques. Létalité augmentée." },
        { "skill_var_myoN4a",  "+5 % létalité" },
        { "skill_name_myoN4b", "Brouillard Copromycète" },
        { "skill_desc_myoN4b", "Un brouillard de spores fongiques enveloppe la région infectée, favorisant une propagation rapide dans les pays voisins." },
        { "skill_var_myoN4b",  "+0.06 propagation régionale" },
    };

    // ── English strings ───────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> EN = new Dictionary<string, string>
    {
        // ── Main Menu ─────────────────────────────────────────────────────────
        { "menu_tagline",        "Dominate the world. One turd at a time." },
        { "menu_play_btn",       "PLAY" },

        // ── Virus Selection Panel ─────────────────────────────────────────────
        { "vsp_title",           "CHOOSE YOUR VIRUS" },
        { "vsp_patient0_title",  "PATIENT ZERO COUNTRY" },
        { "vsp_btn_start_ready", "START THE INFECTION" },
        { "vsp_btn_start_hint",  "Select a virus and a country" },
        { "vsp_loading_title",   "CROTTE VIRUS GENERATION IN PROGRESS" },
        { "vsp_loading_sub",     "Poop Injection in progress..." },

        // Continent filter buttons
        { "continent_all",       "ALL" },
        { "continent_europe",    "EUROPE" },
        { "continent_asia",      "ASIA" },
        { "continent_africa",    "AFRICA" },
        { "continent_northam",   "N. AMER." },
        { "continent_southam",   "S. AMER." },
        { "continent_oceania",   "OCEANIA" },
        { "continent_other",     "OTHER" },

        // Virus data
        { "virus_name_classique",            "La Crottance" },
        { "virus_tagline_classique",         "Classic balanced virus" },
        { "virus_desc_classique",            "Born in the industrial farms of the Beauce plains, La Crottance is a versatile pathogen that adapts to any environment. It thrives in major cities and remote countryside alike." },
        { "virus_caps_classique",            "Balanced transmission · Good cold resistance · Exploits social inequalities" },

        { "virus_name_cacastellaire",        "Cacastellaire" },
        { "virus_tagline_cacastellaire",     "Atmospheric-dispersal pathogen" },
        { "virus_desc_cacastellaire",        "Discovered in low orbit by a malfunctioning spy satellite, Cacastellaire spreads through high-altitude air currents. Airports are its best allies." },
        { "virus_caps_cacastellaire",        "Excellent airborne spread · Bonus on international transit · Low heat resistance" },

        { "virus_name_nanocaca",             "Nano Caca" },
        { "virus_tagline_nanocaca",          "Stealthy and lethal nano-pathogen" },
        { "virus_desc_nanocaca",             "The result of a poorly controlled military bio-engineering experiment, Nano Caca is undetectable by standard health surveillance systems. Its high lethality makes it a formidable adversary." },
        { "virus_caps_nanocaca",             "Invisible to early-detection systems · Lethal day 0 · Slow spread" },

        { "virus_name_fungicaca",            "Fongi-Caca" },
        { "virus_tagline_fungicaca",         "Slow-growing fungal mycosis" },
        { "virus_desc_fungicaca",            "A mutant of Candida auris discovered in the sewage networks of Mumbai, Fongi-Caca thrives in humid and tropical zones. Its total resistance to antifungals makes it nearly untreatable." },
        { "virus_caps_fungicaca",            "Great medical resistance · Thrives in tropical zones · Slow but inexorable growth" },

        // ── Patient Zero Selection Panel ──────────────────────────────────────
        { "pz_title",            "CHOOSE THE TARGET COUNTRY" },
        { "pz_btn_confirm",      "CONFIRM" },

        // ── Skill Tree Menu UI ────────────────────────────────────────────────
        { "skill_tab_transmission",          "Transmission" },
        { "skill_tab_mortalite",             "Mortality" },
        { "skill_tab_special",               "Special" },

        { "skill_info_default_title_transmission", "Transmission" },
        { "skill_info_default_desc_transmission",  "Click a red skill to see its details, then buy it with your Crotogenes. Grey L2 skills unlock after buying L1." },
        { "skill_info_default_desc_special",       "Click a skill to see its details. N2+ skills unlock after buying prerequisites. All Special skills are free." },
        { "skill_coming_soon_desc",                "Content coming soon. This tab will be implemented in a future phase." },

        { "skill_btn_buy_default",           "BUY" },
        { "skill_btn_buy_label",             "Buy" },
        { "skill_btn_already_bought",        "Bought" },
        { "skill_btn_buy_with_cost",         "Buy ({0})" },
        { "skill_cost_display",              "Cost: {0} | Points: {1}" },
        { "skill_cant_buy_suffix",           "{0} (Cannot purchase)" },
        { "skill_prereq_unmet",              "Prerequisites not met for this skill." },
        { "skill_insufficient_points",       "Insufficient points: cost {0}, you have {1}." },
        { "skill_buy_fail_unknown",          "Purchase failed for an unknown reason." },
        { "skill_buy_success_notif",         "AUTONOMOUS VIRAL MUTATION" },

        // ── Top Bar HUD ───────────────────────────────────────────────────────
        { "hud_btn_hide",        "v Hide" },
        { "hud_btn_show",        "^ Show" },
        { "hud_day_label",       "Day {0}" },
        { "hud_btn_slow",        "<< Slow" },
        { "hud_btn_normal",      "Normal" },
        { "hud_btn_pause",       "|| Pause" },
        { "hud_btn_resume",      "> Resume" },
        { "hud_btn_fast",        ">> Fast" },

        // ── Points Display ────────────────────────────────────────────────────
        { "points_label",        "Crotogenes: {0}" },

        // ── End Screen ────────────────────────────────────────────────────────
        { "end_headline_victory",  "EXTINCTION ACHIEVED" },
        { "end_headline_healed",   "THE VACCINE HAS TRIUMPHED" },
        { "end_headline_defeat",   "THE VIRUS IS EXTINCT" },
        { "end_sub_victory",       "Humanity has been annihilated. Your virus completed its mission." },
        { "end_sub_healed",        "Science prevailed. Humanity survived thanks to the vaccine." },
        { "end_sub_defeat",        "Your infection died out before eliminating humanity." },
        { "end_stat_virus",        "Virus: {0}" },
        { "end_stat_turns",        "Game duration: <b>{0}</b> turns" },
        { "end_stat_dead",         "Total deaths    : <b>{0}</b>" },
        { "end_stat_infected",     "Total infected  : <b>{0}</b>" },
        { "end_btn_replay",        "PLAY AGAIN" },

        // ── Status Bar ────────────────────────────────────────────────────────
        { "statusbar_infected",   "Infected: {0}" },
        { "statusbar_vaccine",    "Vaccine: {0}%" },

        // ── Transmission Skills ───────────────────────────────────────────────
        { "skill_name_airborneL1",   "Airborne Diarrhea" },
        { "skill_desc_airborneL1",   "Fecal aerosols reach cruising altitude. Even first-class passengers aren't safe." },
        { "skill_var_airborneL1",    "New bonus modifier for airborne transmission spread." },
        { "skill_name_airborneL2",   "Chemtrails of Contamination" },
        { "skill_desc_airborneL2",   "Chemtrails are real... but they release poop over populations." },
        { "skill_var_airborneL2",    "Airborne spread impact is even stronger." },
        { "skill_name_seaL1",        "Buffet Trap" },
        { "skill_desc_seaL1",        "All-you-can-eat buffets on cruise ships become contamination grounds." },
        { "skill_var_seaL1",         "New bonus modifier for maritime transmission spread." },
        { "skill_name_seaL2",        "Ocean of Filth" },
        { "skill_desc_seaL2",        "Cruise ships are now nothing but giant floating toilets." },
        { "skill_var_seaL2",         "Maritime spread impact is even stronger." },
        { "skill_name_landL1",       "Pump in the Butt" },
        { "skill_desc_landL1",       "An infected person stuck the gas pump in their butt, creating a giant contamination network via gas stations." },
        { "skill_var_landL1",        "New bonus modifier for land transmission spread." },
        { "skill_name_landL2",       "Mario CaCart" },
        { "skill_desc_landL2",       "Exhaust fumes turn roads into contamination highways." },
        { "skill_var_landL2",        "Land spread impact is even stronger." },
        { "skill_name_coldL1",       "Frozen Crotte Survivor" },
        { "skill_desc_coldL1",       "Your virus evolves to thrive in Russian bathrooms. Vodka doesn't kill it." },
        { "skill_var_coldL1",        "New bonus modifier for cold resistance." },
        { "skill_name_coldL2",       "Arctic Poop Master" },
        { "skill_desc_coldL2",       "Siberian strains become your virus's favourite climate. Penguin poop spreads it further." },
        { "skill_var_coldL2",        "Cold resistance impact is even stronger." },
        { "skill_name_heatL1",       "Desert Diarrhea Adaptation" },
        { "skill_desc_heatL1",       "Death Valley bathrooms can't kill this strain. Even scorpion poop carries your virus." },
        { "skill_var_heatL1",        "New bonus modifier for heat resistance." },
        { "skill_name_heatL2",       "Furnace of Filth" },
        { "skill_desc_heatL2",       "Infections thrive at 50°C. Hot liquid waste flows everywhere and contaminates everything that moves." },
        { "skill_var_heatL2",        "Heat resistance impact is even stronger." },
        { "skill_name_bathroomL1",   "No Shower Spray" },
        { "skill_desc_bathroomL1",   "Countries without proper washing systems spread your glory. Dry hands = contaminated hands." },
        { "skill_var_bathroomL1",    "New bonus modifier for poor-hygiene exploitation." },
        { "skill_name_bathroomL2",   "Attack of the Japanese Toilet" },
        { "skill_desc_bathroomL2",   "High-tech bidet malfunctions send germs everywhere. Rich people get wrecked by sentient toilets." },
        { "skill_var_bathroomL2",    "Wealth exploitation impact is even stronger." },
        { "skill_name_dogL1",        "Poodle Pandemic" },
        { "skill_desc_dogL1",        "Dogs develop infected diarrhea. Every public defecation spreads your masterpiece. Pooper scoopers? More like virus dispensers." },
        { "skill_var_dogL1",         "New bonus modifier for dog-vector transmission." },
        { "skill_name_dogL2",        "Great Dane Devastation" },
        { "skill_desc_dogL2",        "Giant dog turds contain viral loads that make laboratories jealous. Street dogs become your unwitting army." },
        { "skill_var_dogL2",         "Dog-vector spread impact is even stronger." },
        { "skill_name_petL1",        "Silent But Deadly" },
        { "skill_desc_petL1",        "Infected humans become walking fart dispensers. Every office, elevator, and bus ride becomes a viral aerosol attack. The smell is your calling card." },
        { "skill_var_petL1",         "New bonus modifier for human digestive gas transmission." },
        { "skill_name_petL2",        "Methane Apocalypse" },
        { "skill_desc_petL2",        "Human digestive systems become biological weapons. Concerts, restaurants, transit crowds — your virus travels on literal hot air." },
        { "skill_var_petL2",         "Human gas transmission impact is even stronger." },
        { "skill_name_flyL1",        "Fly Courier Service" },
        { "skill_desc_flyL1",        "Flies land on feces, then on food. Your virus travels lunch-to-lunch across villages." },
        { "skill_var_flyL1",         "New bonus modifier for fly-vector transmission." },
        { "skill_name_flyL2",        "Insect Army" },
        { "skill_desc_flyL2",        "Trillions of flies become your delivery network. Open sewers = fly breeding grounds = viral paradise." },
        { "skill_var_flyL2",         "Fly-vector spread impact is even stronger." },
        { "skill_name_urineL1",      "Golden Stream" },
        { "skill_desc_urineL1",      "Infected urine contaminates water supplies. Bathroom floors become skating rinks of doom." },
        { "skill_var_urineL1",       "New bonus modifier for contaminated-urine transmission." },
        { "skill_name_urineL2",      "Bladder Blitzkrieg" },
        { "skill_desc_urineL2",      "Urinary tract infections spread your virus with every toilet flush. Water systems worldwide bow to your supremacy." },
        { "skill_var_urineL2",       "Contaminated-urine transmission impact is even stronger." },
        { "skill_name_drugL1",       "Antibiotic Breaker" },
        { "skill_desc_drugL1",       "Penicillin? Cute. Your virus laughs at antibiotics and keeps spreading." },
        { "skill_var_drugL1",        "New bonus modifier for antibiotic resistance." },
        { "skill_name_drugL2",       "Super Bug Evolution" },
        { "skill_desc_drugL2",       "Every antibiotic makes you stronger. Hospitals are your gym. Medical science surrenders." },
        { "skill_var_drugL2",        "Antibiotic resistance impact is even stronger." },
        { "skill_name_vaccineL1",    "ViteMaDose" },
        { "skill_desc_vaccineL1",    "The virus fears no one, not even the naturally immune." },
        { "skill_var_vaccineL1",     "New bonus modifier for vaccine immunity bypass." },
        { "skill_name_vaccineL2",    "Immunity? Lol." },
        { "skill_desc_vaccineL2",    "Herd immunity is a myth. Your virus treats antibodies like appetizers." },
        { "skill_var_vaccineL2",     "Vaccine bypass impact is even stronger." },
        { "skill_name_vaccineSabotageL1", "Poop in the Pipettes" },
        { "skill_desc_vaccineSabotageL1", "A mysterious fecal perfume invades the lab. Researchers keep sneezing and dropping samples in panic." },
        { "skill_var_vaccineSabotageL1",  "New modifier for vaccine research slowdown." },
        { "skill_name_vaccineSabotageL2", "Bacteriological Toilet War" },
        { "skill_desc_vaccineSabotageL2", "The scientists' coffee machine now smells like apocalypse. Between toilet emergencies and contaminated gloves, the vaccine team crawls at snail speed." },
        { "skill_var_vaccineSabotageL2",  "Vaccine research slowdown impact is even stronger." },
        { "skill_name_fusionBioBidetL3",    "Bio-Bidet Catastrophe" },
        { "skill_desc_fusionBioBidetL3",    "Bidets, urine trails, and plumbing systems sync into one global contamination engine." },
        { "skill_var_fusionBioBidetL3",     "Hygiene exploitation and urine transmission impacts are even stronger." },
        { "skill_name_fusionMethaneBurstL3", "Methane Vector Burst" },
        { "skill_desc_fusionMethaneBurstL3", "Human farts no longer disperse in the air, creating contamination clouds that spread rapidly." },
        { "skill_var_fusionMethaneBurstL3",  "Human gas and airborne transmission impacts are even stronger." },
        { "skill_name_fusionCanineAirliftL3", "Canine Fecal Airlift" },
        { "skill_desc_fusionCanineAirliftL3", "Flies carry infected dog droppings across the world, enabling rapid viral spread." },
        { "skill_var_fusionCanineAirliftL3",  "Dog-vector, fly-vector, and hygiene exploitation impacts are even stronger." },

        // ── Mortalité Skills ──────────────────────────────────────────────────
        { "skill_name_anusL1",   "Spontaneous Anal Fissures" },
        { "skill_desc_anusL1",   "The rectal epithelium tears spontaneously. Every bowel movement causes minor bleeding. The immune system begins to fail under constant inflammation." },
        { "skill_var_anusL1",    "Increased mortality, with reinforced bonus in cold countries." },
        { "skill_name_anusL2",   "Complete Mucosal Prolapse" },
        { "skill_desc_anusL2",   "The rectal mucosa collapses and is expelled. The sphincters can no longer hold anything. Doctors don't know what to do anymore." },
        { "skill_var_anusL2",    "Even higher mortality, especially in cold countries." },
        { "skill_name_anusL3",   "Sphincter Necrosis" },
        { "skill_desc_anusL3",   "Rectal tissue dies. The entire lower gastrointestinal system becomes an open wound. Gangrene sets in." },
        { "skill_var_anusL3",    "Maximum hemorrhage: very high mortality in cold climates, excellent lethality base everywhere." },
        { "skill_name_poumonL1", "Chronic Methanic Reflux" },
        { "skill_desc_poumonL1", "Intestinal gases rise up into the lungs. Every breath smells and burns. Vital capacity declines by 5% per day." },
        { "skill_var_poumonL1",  "Respiratory damage boosted in hot or arid climates." },
        { "skill_name_poumonL2", "Bronchial Solidification" },
        { "skill_desc_poumonL2", "Fecal matter hardens inside the bronchial tubes. Coughing produces brown clots. Hypoxia begins. Patients slowly suffocate." },
        { "skill_var_poumonL2",  "More violent asphyxia, especially in hot/arid climates." },
        { "skill_name_poumonL3", "Fecal Pulmonary Flood" },
        { "skill_desc_poumonL3", "The alveoli fill with intestinal fluid. The patient can no longer breathe normally. Internal drowning is inevitable." },
        { "skill_var_poumonL3",  "Extreme asphyxia: mortality peak in hot/arid climates." },
        { "skill_name_bouffeL1", "Crop Infiltration" },
        { "skill_desc_bouffeL1", "Agricultural crops are contaminated by viral manure. Harvests become passive vectors." },
        { "skill_var_bouffeL1",  "Food contamination most effective in low-hygiene regions." },
        { "skill_name_bouffeL2", "Corrupted Supply Chain" },
        { "skill_desc_bouffeL2", "Food factories have become incubators. Each processing step amplifies the viral load." },
        { "skill_var_bouffeL2",  "Food contamination amplified in low-hygiene countries, even more in hot climates." },
        { "skill_name_bouffeL3", "World Market Apocalypse" },
        { "skill_desc_bouffeL3", "Every food on earth is infected. From field to plate, everything is contaminated. Famine kills before disease does." },
        { "skill_var_bouffeL3",  "Maximum contamination: extremely punishing in low hygiene, with bonus in hot climates." },
        { "skill_name_cerveauL1", "Fecal Encephalitis" },
        { "skill_desc_cerveauL1", "Fecal bacteria breach the blood-brain barrier. The brain gently marinates in filth." },
        { "skill_var_cerveauL1",  "Mental damage active mostly in wealthy countries." },
        { "skill_name_cerveauL2", "Dark Brown Cranial Pressure" },
        { "skill_desc_cerveauL2", "Brain cavities fill with brown matter. Eyes start to seep. The colour is indescribable." },
        { "skill_var_cerveauL2",  "Brain colonisation reinforced in wealthy countries." },
        { "skill_name_cerveauL3", "Terminal Ocular Excretion" },
        { "skill_desc_cerveauL3", "The brain empties through the eye sockets. Tears are now a disturbing shade of brown. Neurologists have given up." },
        { "skill_var_cerveauL3",  "Major mental damage: maximum effect in wealthy countries." },
        { "skill_name_folieL1",   "Digestive Psychosis" },
        { "skill_desc_folieL1",   "Intestinal neurotransmitters invade the brain. The boundary between desires and instincts fades." },
        { "skill_var_folieL1",    "Fecal madness: mental damage mostly visible in wealthy countries." },
        { "skill_name_folieL2",   "Stercoral Delirium" },
        { "skill_desc_folieL2",   "The patient sees colours that toilets should not have. Hallucinations guaranteed. Staying calm is useless." },
        { "skill_var_folieL2",    "Reinforced fecal madness, especially in wealthy countries." },
        { "skill_name_folieL3",   "Terminal Latrine Dementia" },
        { "skill_desc_folieL3",   "The patient is convinced they are a toilet. Final phase: they try to use themselves." },
        { "skill_var_folieL3",    "Terminal dementia: maximum mental pressure in wealthy countries." },
        { "skill_name_fusionLiquefactionL4", "Total Fecal Liquefaction" },
        { "skill_desc_fusionLiquefactionL4", "Body disintegrates through all vectors. Hemorrhagic feces, breathing excrement, bleeding food. Total disintegration." },
        { "skill_var_fusionLiquefactionL4",  "Anus+Lung Fusion: massive lethality in cold countries and hot/arid zones." },
        { "skill_name_fusionApothéoseL4",    "Excretory Mental Apotheosis" },
        { "skill_desc_fusionApothéoseL4",    "A poop brain that drives you insane. The patient expels their thoughts through the anus. Consciousness dissolves into feces. Absolute dementia." },
        { "skill_var_fusionApothéoseL4",     "Brain+Madness Fusion: extreme mental damage, mostly active in wealthy countries." },
        { "skill_name_fusionContaminationL4", "Psycho-Respiratory Contamination" },
        { "skill_desc_fusionContaminationL4", "Internal drowning, food poisoning, and dementia simultaneously. Madness worsens every breath; every bite becomes delirium. Triple asphyxia." },
        { "skill_var_fusionContaminationL4",  "Lung+Food Fusion: enormous pressure in hot/arid climates and low-hygiene especially if hot." },

        // ── Special Skills ────────────────────────────────────────────────────
        { "skill_name_claN1",  "CrotteSpreading Evolution" },
        { "skill_desc_claN1",  "The virus evolves continuously to infect as many humans as possible. Each turn, 2% chance to automatically assimilate a transmission skill." },
        { "skill_var_claN1",   "2% chance/turn: auto-unlock a Transmission skill" },
        { "skill_name_claN2a", "Drool of Filth" },
        { "skill_desc_claN2a", "The virus has impregnated the saliva of all dogs. Canine and animal spread improved." },
        { "skill_var_claN2a",  "+0.09 Dog and Animal modifier" },
        { "skill_name_claN2b", "Flaquacaca" },
        { "skill_desc_claN2b", "Even simple innocent puddles of water are now a means of propagation. Land spread improved." },
        { "skill_var_claN2b",  "+0.07 Land Transport modifier" },
        { "skill_name_claN3",  "Coprogenous Prime" },
        { "skill_desc_claN3",  "Every infection now pays a permanent biological rent. Definitive point-gain bonus for the entire game." },
        { "skill_var_claN3",   "+22% permanent point gain" },
        { "skill_name_claN4a", "Invasive Colic" },
        { "skill_desc_claN4a", "The last mutation turns colics into systemic hemorrhage. Lethality increased." },
        { "skill_var_claN4a",  "+3.5% lethality" },
        { "skill_name_claN4b", "Septic Scab" },
        { "skill_desc_claN4b", "In unsanitary environments, the virus develops a biological grime layer that multiplies its virulence." },
        { "skill_var_claN4b",  "+0.06 Hygiene exploitation" },
        { "skill_name_casN1",  "Spatial Dispersal" },
        { "skill_desc_casN1",  "Through an orbital defecation phenomenon, the virus instantly disseminates into 5 random uninfected countries upon purchase." },
        { "skill_var_casN1",   "Immediately infects 5 random countries (1 person each)" },
        { "skill_name_casN2a", "Orbital Shit Dust" },
        { "skill_desc_casN2a", "Cosmic defecation particles infiltrate planes and ships effortlessly." },
        { "skill_var_casN2a",  "+0.10 Airborne transport | +0.08 Maritime transport" },
        { "skill_name_casN2b", "Coproid Plasma" },
        { "skill_desc_casN2b", "The extraterrestrial origin confers resistance to extreme temperatures." },
        { "skill_var_casN2b",  "+0.05 Heat resistance | +0.05 Cold resistance" },
        { "skill_name_casN3",  "Astral Evolutionary Transmission" },
        { "skill_desc_casN3",  "The cosmic signal permanently anchors itself in the virus: 2% permanent chance per turn to automatically assimilate a transmission skill." },
        { "skill_var_casN3",   "+2% chance/turn permanent: auto-unlock a Transmission skill" },
        { "skill_name_casN4a", "Necrotic Halo" },
        { "skill_desc_casN4a", "The cosmic death aura irradiates tissues, increasing the virus's lethality." },
        { "skill_var_casN4a",  "+4% lethality" },
        { "skill_name_casN4b", "Fecal Gravity" },
        { "skill_desc_casN4b", "A space virus has no limits; borders cannot contain it." },
        { "skill_var_casN4b",  "+0.07 cross-border spread" },
        { "skill_name_nanN1",  "Patient Zero Injection" },
        { "skill_desc_nanN1",  "An autonomous nano-carrier discreetly infiltrates an uninfected country and deposits exactly 1 asymptomatic carrier." },
        { "skill_var_nanN1",   "Immediately infects 1 person in a random uninfected country" },
        { "skill_name_nanN2a", "Pharmaceutical Shielding" },
        { "skill_desc_nanN2a", "Nano-shells reinforce the viral membrane against antivirals. Treatments lose their effectiveness." },
        { "skill_var_nanN2a",  "+0.10 drug resistance" },
        { "skill_name_nanN2b", "Optimised Auto-Replication" },
        { "skill_desc_nanN2b", "Nano-sensors optimise the replication rate in real time. Infection growth accelerates." },
        { "skill_var_nanN2b",  "+0.08 infection growth multiplier" },
        { "skill_name_nanN3",  "Autonomous KillerPoop Mutation" },
        { "skill_desc_nanN3",  "Nano-viral processors permanently anchor themselves and continuously forge new deadly symptoms." },
        { "skill_var_nanN3",   "+4% chance/turn permanent: auto-unlock a Mortality skill" },
        { "skill_name_nanN4a", "Colonisation Swarm" },
        { "skill_desc_nanN4a", "Nano-viruses prioritise wealthy individuals whose social networks ensure maximum dissemination." },
        { "skill_var_nanN4a",  "+0.06 Wealth exploitation" },
        { "skill_name_nanN4b", "Sphincter-0 Protocol" },
        { "skill_desc_nanN4b", "The final protocol bypasses genetic immune defences while increasing lethal virulence." },
        { "skill_var_nanN4b",  "+4% lethality | +4% Immunity bypass" },
        { "skill_name_myoN1",  "Spore Mutation" },
        { "skill_desc_myoN1",  "The viral mycelium sporulates spontaneously. 2% chance per turn to acquire a lethal symptom." },
        { "skill_var_myoN1",   "2% chance/turn: auto-unlock a Mortality skill" },
        { "skill_name_myoN2a", "Sewer Network" },
        { "skill_desc_myoN2a", "The fungus colonises the sewer networks. Low-hygiene environments become perfect incubators." },
        { "skill_var_myoN2a",  "+0.09 Hygiene exploitation" },
        { "skill_name_myoN2b", "Intestinal Roots" },
        { "skill_desc_myoN2b", "Viral hyphae anchor deep into intestinal tissues, accelerating infection growth." },
        { "skill_var_myoN2b",  "+0.07 infection growth" },
        { "skill_name_myoN3",  "Difficult Synthesis" },
        { "skill_desc_myoN3",  "The fungus produces proteins mimicking natural antibodies, making vaccine development extremely complex. Vaccine cap raised to 115%." },
        { "skill_var_myoN3",   "Vaccine cap raised to 115%" },
        { "skill_name_myoN4a", "Fungal-Fecal Bloom" },
        { "skill_desc_myoN4a", "In humid environments, viral spores bloom into necrotic agents. Lethality increased." },
        { "skill_var_myoN4a",  "+5% lethality" },
        { "skill_name_myoN4b", "Copromycete Fog" },
        { "skill_desc_myoN4b", "A fog of fungal spores envelops the infected region, promoting rapid spread to neighbouring countries." },
        { "skill_var_myoN4b",  "+0.06 regional spread" },
    };
}
